# Generated by Django 4.2.4 on 2023-12-15 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the department",
                        max_length=80,
                        verbose_name="name",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the position",
                        max_length=80,
                        verbose_name="title",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="The department of this position",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="library_staff.department",
                    ),
                ),
            ],
            options={
                "ordering": ["department", "title"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "friendly_name",
                    models.CharField(
                        help_text="The person's first name or a nick name",
                        max_length=50,
                        verbose_name="friendly name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="The person's last name",
                        max_length=50,
                        verbose_name="last name",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="The legal first name and last name, optional middle names and additional name parts, of the staff member",
                        max_length=80,
                        verbose_name="full name",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "friendly_name"],
            },
        ),
        migrations.CreateModel(
            name="StaffPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        help_text="The position filled by the staff member",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_staff.position",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="The staff member assicated with the position",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_staff.member",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
