# Generated by Django 4.2.4 on 2023-12-16 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the type', max_length=80, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssignableTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.ForeignKey(help_text='The ', on_delete=django.db.models.deletion.CASCADE, to='library_staff.member')),
            ],
        ),
        migrations.CreateModel(
            name='Assignable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the type', max_length=80, verbose_name='name')),
                ('type', models.ForeignKey(blank=True, help_text='The type of this assignable item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_staff.assignabletype')),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
    ]
