# Generated by Django 4.2.4 on 2023-12-17 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_staff', '0002_assignabletype_assignableto_assignable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-level', 'department', 'title']},
        ),
        migrations.RemoveField(
            model_name='assignableto',
            name='Position',
        ),
        migrations.AddField(
            model_name='assignableto',
            name='Responsible',
            field=models.ForeignKey(blank=True, help_text='The position responsible to ensure the person has received the assignable item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibility', to='library_staff.position'),
        ),
        migrations.AddField(
            model_name='assignableto',
            name='assignable',
            field=models.ForeignKey(default=0, help_text='The assignable item assignable to the position', on_delete=django.db.models.deletion.CASCADE, to='library_staff.assignable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='level',
            field=models.IntegerField(default=0, help_text='An automatically generated number to help with ordering', verbose_name='level'),
        ),
        migrations.AddField(
            model_name='position',
            name='reports_to',
            field=models.ForeignKey(blank=True, help_text='The position that this position reports to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_staff.position', verbose_name='reports to'),
        ),
        migrations.AddField(
            model_name='assignableto',
            name='position',
            field=models.ForeignKey(default=0, help_text='The position to receive the item', on_delete=django.db.models.deletion.CASCADE, related_name='assignable_item', to='library_staff.position'),
            preserve_default=False,
        ),
    ]
